---
title: "Metodologia Badań Psychologicznych 02"
author: "Krzysztof Basiński"
output: 
  revealjs::revealjs_presentation:
    theme: serif
    center: true
    incremental: true
---


# Zmienne i hipotezy


## Zmienne
- Zmienna -  jakakolwiek własność lub cecha, która przyjmuje różne wartości u różnych ludzi, w różnych sytuacjach etc.
- Przykłady:
    - Wiek
    - Płeć
    - Nastrój
    - Agresywność
    - Inteligencja
    - Neurotyzm


## Operacjonalizacja zmiennej
- Nie wszystkie pojęcia (zmienne konceptualne) można wprost badać empirycznie
- Przykłady - inteligencja, osobowość, poczucie kontroli
- Operacjonalizacja to definiowanie zmiennej przez pryzmat obiektywnych, empirycznych wskaźników (np. wynik testu na inteligencję)
- Definicja operacyjna: np. inteligencja = wynik testu Wechslera


## Typy zmiennych
- Zmienne jakościowe
- Zmienne ilościowe


## Typy zmiennych (skal pomiarowych)
- Zmienne kategorialne (*categorial*)
- Zmienne ciągłe (*continous*)


## Zmienne kategorialne: typy
- Zmienna nominalna (*nominal*) – dwie lub więcej kategorii, jednak kategorie są **nieuporządkowane**
- Zmienna dychotomiczna (*dichotomous*) – specjalny rodzaj nominalnej, przybiera tylko **dwie**, przeciwstawne kategorie
- Zmienna porządkowa (*ordinal*)– kategorie można uporządkować, jednak nie można porównywać ich ze sobą


## Zmienne ciągłe: typy
- Zmienna przedziałowa (*interval*) – zmienna przybiera wymierne wartości, które można porównywać
- Zmienna ilorazowa, stosunkowa (*ratio*) – zmienna przedziałowa z punktem zerowym (można powiedzieć, że czegoś jest np. „dwa razy więcej”)




## Hipotezy
- Teorie są najczęściej "za duże", żeby je w całości weryfikować za pomocą pojedynczych badań
- Hipoteza badawcza - konkretna, falsyfikowalna predykcja na temat związku pomiędzy dwiema lub więcej *zmiennymi*
- Hipoteza zakłada *związek* pomiędzy zmiennymi i najczęściej mówi o *kierunku* tego związku

## Przykłady hipotez badawczych
#. Neurotyzm wiąże się z większym ryzykiem psychopatologii
#. Wysoki poziom lęku wiąże się z krótszym zwlekaniem z podjęciem leczenia onkologicznego
#. Słuchanie muzyki *zmniejsza* natężenie odczuwanego bólu
#. Słuchanie muzyki *zwiększa* natężenie odczuwanego bólu


## Hipotezy kierunkowe
- Hipoteza kierunkowa to taka, która zakłada *kierunek zależności* między dwoma zmiennymi
- W takiej hipotezie mamy zmienną / zmienne niezależne (*predyktory*) i zmienną zależną (*outcome*)
- Zmienna niezależna **wyjaśnia zmienność** zmiennej zależnej


## Populacja i próba
- *Populacja* - ogół osób, do których odnosi się dana teoria psychologiczna (np. populacja wszystkich ludzi, populacja kobiet, populacja niemowląt)
- Najczęściej nie możemy zbadać całej populacji ze względów praktycznych
- Badamy tylko określona cześć populacji - *próbę*
- Jest wiele różnych metod *doboru próby*


## Próba a populacja
- Skąd wiemy, że zależność wykryta w próbie jest obecna w populacji?
- Nie wiemy
- Możemy przypuszczać z określonym *prawdopodobieństwem*
- Do określenia tego prawdopodobieństwa potrzebujemy testów statystycznych

